# Generated by Django 3.2.18 on 2023-03-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(default="1998-11-18"),
        ),
    ]
